server.port=8082

spring.datasource.url=jdbc:mysql://localhost:3306/quizdb
spring.datasource.username=root
spring.datasource.password=7548
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Forces Hibernate to recreate tables to match Java code exactly
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# MUST HAVE for Spring Boot 3 + data.sql
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
logging.level.org.hibernate.SQL=DEBUG
